### ISSUE TITLE
Unable to connect : SSL Handshake failed.

### ISSUE THREAD

**Issue by cerw** [noodlewerk/NWPusher#10]
I have download the Certificate exported all that and still can not connect to server/ How to troubleshoot this?
Thanks

**Comment by eaigner** [comment]
Same issue here, don't know how to get it to connect.

**Comment by leonardvandriel** [comment]
Hi, please tell me a bit more about what you tried and where you get stuck:

- are you using the pusher application or the framework directly?
- what is the exact error message that is reported by the application or framework?
- did you try to connect on a different network, e.g. different WiFi connection?

Thanks

**Comment by leonardvandriel** [comment]
eaigner, could you update to the latest (0.6.1) release and give it another try? I added some extra SSL handshake error codes that should make the error message more descriptive. Thanks.

**Comment by s3lvin** [comment]
Unable to connect SSL handshake failed (-25320) 

is the error I am getting. Any solutions?

**Comment by leonardvandriel** [comment]
Hi @s3lvin, thanks for reporting this one. Apple's documentation says: "errSecInDarkWake - The user interface could not be displayed because the system is in a dark wake state".

Apparently this 'dark wake' was introduced in Lion, allowing Mac OS to wake up from sleep through network activity. I'm guessing that the keychain is not fully accessible in this state. Might this be the case?
