### ISSUE TITLE
Notification error: APN invalid token

### ISSUE THREAD

**Issue by louisyip** [noodlewerk/NWPusher#15]
Hello, when I try to use APN Production SSL Certificate to do Push Notifications it failed and got "Notification error: APN invalid token". But if I use Development SSL Certificate it work fine!! 

Did any one know what is the problem in it?
thanks a lot!!

**Comment by pradipSpaceo** [comment]
I am facing the same issue. I get problem when I use Development SSL Certificate.

**Comment by kvaeng** [comment]
Same problem with development certificate.

**Comment by leonardvandriel** [comment]
Just to be sure: Are you using separate device tokens for production and development? The same device has different device tokens for different certificates. This is often a source of confusion, see https://github.com/noodlewerk/NWPusher#troubleshooting.

**Comment by leonardvandriel** [comment]
I'm closing the issue for now. If anyone finds this issue persists, please let me know.

**Comment by olivaresf** [comment]
I just had this happen to me. Interestingly enough, I was trying with the development certificate and I was consistently getting `Invalid APN Token` errors. I re-created the certificate and then exported, and it didn't work.

What I did to solve it was go and turn on Project > Capabilities > Push Notification. When I turned it on, my app wouldn't run because of entitlements so I deleted the app from the device, cleaned, relaunched and I stopped getting the errors. No idea why, but that did the trick. Hope it helps anyone that finds this thread!

**Comment by vtellez** [comment]
same issue here

**Comment by danat8x8** [comment]
I am having the same issue, but the posts above fail to help.
I have enabled the Push Notification capability, cleaned and rebuilt, but it's not working "APN invalid token".  Could it be due to that fact that I am using

**Comment by danat8x8** [comment]
Sorry for the cliffhanger :)
I'm using VOIP and with iOS9, PushKit has now been integrated into the old remote notifications.  Could this be the sources of my issues?

**Comment by goa** [comment]
Make sure you have followed the instructions in the README.MD exactly so that you know exactly which kind of certificate you are using (development / production).

Also, the token will be logged in a form similar to this one:

_<12345678 abcdef12 87654321 12345678 abcdef12 87654321 12345678>_

When you paste it in the Pusher app textfield, make sure to remove spaces and <>'s.
So the above, becomes: 

**12345678abcdef128765432112345678abcdef128765432112345678**

**Comment by ericcheungwork** [comment]
I solved this by regenerate the certificate of push notification for my app id again. 
(I used the wrong .p12 for another app id)
