### ISSUE TITLE
SSL handshake failed (-9829)

### ISSUE THREAD

**Issue by khunglongbeo** [noodlewerk/NWPusher#32]
Hello !

Thanks for NWPusher, it really nice for my work !

But today, i get this error "SSL handshake failed (-9829)", and my app crash. 

Problem is, not alway crash when app run. Sometime it error, sometime it OK

This my code (swift)
![error](https://cloud.githubusercontent.com/assets/21083703/18612208/ef57aa8a-7d7d-11e6-8a40-3c7c845323bb.png)

This error
![screen shot 2016-09-18 at 8 53 44 am](https://cloud.githubusercontent.com/assets/21083703/18612201/a6a9aed2-7d7d-11e6-9eff-67475efe49e3.png)

Sorry my bad English !

Thanks for support !

Regard !

**Comment by leonardvandriel** [comment]
Hi. Error -9829 is described in `SecureTransport.h` with "The certificate is unknown" (`errSSLPeerCertUnknown`). A similar issue has been reported two years ago: https://github.com/noodlewerk/NWPusher/issues/8. I believe the problem there was that the file contained multiple certificates. Can you take a look there and see if your issue is related?
