### ISSUE TITLE
if i'm not a developer, can i play around with it using jnust my mac & iphone? :beer:

### ISSUE THREAD

**Issue by zzz6519003** [noodlewerk/NWPusher#58]

**Comment by leonardvandriel** [comment]
Hi @zzz6519003, you don't need to consider yourself a developer in order to be able to send push notifications. However, there are some technical challenges ahead of you. NWPusher does not rely on any other external services apart from the Apple Developer portal website.

The biggest challenge as a non-developer will be obtaining the device token of your iPhone, which is the "address" of your iPhone to which NWPusher will send your message. All steps are described in detail in the [README](https://github.com/noodlewerk/NWPusher/blob/master/README.md). You will need the Mac application called XCode for this. These are the minimal steps necessary.

Note that you can only send push notification to your own apps. That's why you will need your own Apple Developer account and create your own app from scratch in order to send and receive any notifications.

Cheers.
